version: 2
jobs:
  build:
    # This doesn't work, because gh-pages branch doesn't have .circleci config.
    # Build can be skipped by adding [skip-ci] to commit message.
    # branches:
    #   ignore:
    #     - gh-pages

    docker:
      - image: circleci/node:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - '4d:ba:21:a2:05:09:11:4f:0d:6a:83:be:3f:d2:8c:08'

      - checkout

      - restore_cache:
          key: node-modules-{{ checksum "yarn.lock" }}

      - run: yarn

      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run: yarn build

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.email tomas.ehrlich@gmail.com
              git config --global user.name "Tomáš Ehrlich"
              yarn deploy
            fi
